### ISSUE TITLE
[Schema Inaccuracy] Unable to generate code as per current description

### ISSUE THREAD

**Issue by alancosta-iress** [github/rest-api-description#1206]
# Schema Inaccuracy

## Expected
Expected to generate a client from csharp-netcore generator as per [Open API Generator](https://openapi-generator.tech/docs/generators/csharp-netcore)

Failed when generating `issues_add_labels_request`

### Input
[api.github.com.yaml](https://raw.githubusercontent.com/github/rest-api-description/main/descriptions/api.github.com/api.github.com.yaml)

### Config
genconfig.yaml
```yaml
generatorName: csharp-netcore
outputDir: /local/output
inputSpec: /local/input/api.github.com.yaml
library: httpclient
additionalProperties:
  packageName: GHOpenApi
  targetFramework: netcoreapp3.1
  excludeTests: true
  sourceFolder: .
  supportsAsync: false
```
### Command
```powershell
$ docker run --rm -v ${PWD}:/local openapitools/openapi-generator-cli generate --config /local/input/genconfig.yaml
```

### Error
```log
Exception in thread "main" java.lang.RuntimeException: Could not generate model 'issues_add_labels_request'
        at org.openapitools.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:536)
        at org.openapitools.codegen.DefaultGenerator.generate(DefaultGenerator.java:892)
        at org.openapitools.codegen.cmd.Generate.execute(Generate.java:449)
        at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
        at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
Caused by: java.lang.StringIndexOutOfBoundsException: begin 0, end 1, length 0
        at java.base/java.lang.String.checkBoundsBeginEnd(Unknown Source)
        at java.base/java.lang.String.substring(Unknown Source)
        at org.openapitools.codegen.templating.mustache.TitlecaseLambda.titleCase(TitlecaseLambda.java:64)
        at org.openapitools.codegen.templating.mustache.TitlecaseLambda.execute(TitlecaseLambda.java:80)
        at com.samskivert.mustache.Mustache$SectionSegment.execute(Mustache.java:874)
        at com.samskivert.mustache.Mustache$BlockSegment.executeSegs(Mustache.java:845)
        at com.samskivert.mustache.Mustache$SectionSegment.execute(Mustache.java:870)
        at com.samskivert.mustache.Mustache$BlockSegment.executeSegs(Mustache.java:845)
        at com.samskivert.mustache.Mustache$InvertedSegment.execute(Mustache.java:910)
        at com.samskivert.mustache.Mustache$BlockSegment.executeSegs(Mustache.java:845)
        at com.samskivert.mustache.Mustache$SectionSegment.execute(Mustache.java:866)
        at com.samskivert.mustache.Mustache$BlockSegment.executeSegs(Mustache.java:845)
        at com.samskivert.mustache.Mustache$SectionSegment.execute(Mustache.java:881)
        at com.samskivert.mustache.Template.executeSegs(Template.java:157)
        at com.samskivert.mustache.Mustache$IncludedTemplateSegment.execute(Mustache.java:774)
        at com.samskivert.mustache.Mustache$BlockSegment.executeSegs(Mustache.java:845)
        at com.samskivert.mustache.Mustache$SectionSegment.execute(Mustache.java:870)
        at com.samskivert.mustache.Mustache$BlockSegment.executeSegs(Mustache.java:845)
        at com.samskivert.mustache.Mustache$SectionSegment.execute(Mustache.java:866)
        at com.samskivert.mustache.Mustache$BlockSegment.executeSegs(Mustache.java:845)
        at com.samskivert.mustache.Mustache$InvertedSegment.execute(Mustache.java:910)
        at com.samskivert.mustache.Mustache$BlockSegment.executeSegs(Mustache.java:845)
        at com.samskivert.mustache.Mustache$SectionSegment.execute(Mustache.java:881)
        at com.samskivert.mustache.Mustache$BlockSegment.executeSegs(Mustache.java:845)
        at com.samskivert.mustache.Mustache$SectionSegment.execute(Mustache.java:866)
        at com.samskivert.mustache.Template.executeSegs(Template.java:157)
        at com.samskivert.mustache.Template.execute(Template.java:134)
        at com.samskivert.mustache.Template.execute(Template.java:125)
        at org.openapitools.codegen.templating.MustacheEngineAdapter.compileTemplate(MustacheEngineAdapter.java:65)
        at org.openapitools.codegen.TemplateManager.write(TemplateManager.java:163)
        at org.openapitools.codegen.DefaultGenerator.processTemplateToFile(DefaultGenerator.java:1038)
        at org.openapitools.codegen.DefaultGenerator.processTemplateToFile(DefaultGenerator.java:1025)
        at org.openapitools.codegen.DefaultGenerator.generateModel(DefaultGenerator.java:393)
        at org.openapitools.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:527)
        ... 4 more
```

**Comment by bearcherian** [comment]
@alancosta-iress I did run into a similar error when running the following command
```
docker run --rm -v "${PWD}:/local" openapitools/openapi-generator-cli generate -i https://raw.githubusercontent.com/github/rest-api-description/main/descriptions/api.github.com/api.github.com.yaml -g csharp-netcore -o /local/output/netcore
```

but when I changed target language to Go, I got a successful pass

```
docker run --rm -v "${PWD}:/local" openapitools/openapi-generator-cli generate -i https://raw.githubusercontent.com/github/rest-api-description/main/descriptions/api.github.com/api.github.com.yaml -g go -o /local/output/go
```

So it seems like an issue with the `openapi-generator-cli` code for generating the `csharp-netcore` models. I'd suggest opening an issue with their project and see if they can narrow down the cause of the error.
