### ISSUE TITLE
[Schema Inaccuracy] When tried to use openapi-to-graphql, I got errors

### ISSUE THREAD

**Issue by jiheapark** [github/rest-api-description#1330]
# Schema Inaccuracy

I tried to convert github rest api openapi docs to graphql.
https://raw.githubusercontent.com/github/rest-api-description/main/descriptions/api.github.com/api.github.com.json
used openapi-to-graphql(https://www.npmjs.com/package/openapi-to-graphql)

```
/Users/user/Desktop/n3r/web-ui/node_modules/dist/openapi-to-graphql/src/schema_builder.js:353
    const itemsSchema = itemDef.schema;
                                ^
TypeError: Cannot read properties of undefined (reading 'schema')
    at createOrReuseList (/Users/user/Desktop/n3r/web-ui/node_modules/dist/openapi-to-graphql/src/schema_builder.js:353:33)
    at getGraphQLType (/Users/user/Desktop/n3r/web-ui/node_modules/dist/openapi-to-graphql/src/schema_builder.js:88:20)
    at getFieldForOperation (/Users/user/Desktop/n3r/web-ui/node_modules/dist/openapi-to-graphql/src/index.js:540:18)
    at addQueryFields (/Users/user/Desktop/n3r/web-ui/node_modules/dist/openapi-to-graphql/src/index.js:268:19)
    at /Users/user/Desktop/n3r/web-ui/node_modules/dist/openapi-to-graphql/src/index.js:153:13
    at Array.forEach (<anonymous>)
    at translateOpenAPIToGraphQL (/Users/user/Desktop/n3r/web-ui/node_modules/dist/openapi-to-graphql/src/index.js:149:37)
    at createGraphQLSchema (/Users/user/Desktop/n3r/web-ui/node_modules/dist/openapi-to-graphql/src/index.js:72:16)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

## Expected

Get graphql schemas correctly.
I want to make graphql schema by opeanpi docs.
what should I do?
Please help me.

**Comment by dinonuggies1** [comment]
👋🏽  Hi! The public `rest-api-description` is intended to be a reflection of our [REST API](https://docs.github.com/en/rest) services -- not GraphQL. We do not guarantee parity between the two. Apologies for any confusion there. 

We do, however, have a separate means of acquiring the schema for our GraphQL service. You can achieve this through introspection. For more information, check out our documentation [here](https://docs.github.com/en/graphql/overview/public-schema) for specifics. Hope that helps!

**Comment by jiheapark** [comment]
@dinonuggies1 
Thank you for your answer.

But... public shcema you linked is not the same as rest api, right?
For example, if I want to get repository contents by `GET /repos/{owner}/{repo}/contents/{path}`(https://docs.github.com/en/rest/repos/contents), where is the query for the rest api?
How can I get contents of repository by graphql??
