### ISSUE TITLE
[Schema Inaccuracy] attribute components.schemas.[pages-https-certificate|audit-log-event].items is missing

### ISSUE THREAD

**Issue by er1c** [github/rest-api-description#335]
# Schema Inaccuracy

```
Exception in thread "main" org.openapitools.codegen.SpecValidationException: There were issues with the specification. The option can be disabled via validateSpec (Maven/Gradle) or --skip-validate-spec (CLI).
 | Error count: 2, Warning count: 0
Errors:
	-attribute components.schemas.pages-https-certificate.items is missing
	-attribute components.schemas.audit-log-event.items is missing

	at org.openapitools.codegen.config.CodegenConfigurator.toContext(CodegenConfigurator.java:546)
	at org.openapitools.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:573)
	at org.openapitools.codegen.cmd.Generate.execute(Generate.java:433)
	at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
	at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
```

## Expected

I expected the schema to pass the opentools validation.

## Reproduction Steps

    curl -o api.github.com.v3.1.yaml \
      https://raw.githubusercontent.com/github/rest-api-description/main/descriptions/ghes-3.1/ghes-3.1.yaml

    docker run --rm \
        -v $PWD:/local openapitools/openapi-generator-cli generate \
        -i /local/api.github.com.v3.1.yaml \
        -g scala-sttp \
        -o /local/client/github

**Comment by er1c** [comment]
It now triggers: 

```
xception in thread "main" java.lang.RuntimeException: Could not generate model 'code-scanning-alert-dismissed-reason'
	at org.openapitools.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:544)
	at org.openapitools.codegen.DefaultGenerator.generate(DefaultGenerator.java:875)
	at org.openapitools.codegen.cmd.Generate.execute(Generate.java:441)
	at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
	at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
Caused by: java.lang.NullPointerException: Null context for variable 'fnEnumEntry' on line 34
	at com.samskivert.mustache.Template.getValueIn(Template.java:288)
	at com.samskivert.mustache.Template.getValue(Template.java:224)
	at com.samskivert.mustache.Template.getSectionValue(Template.java:269)
	at com.samskivert.mustache.Mustache$SectionSegment.execute(Mustache.java:859)
	at com.samskivert.mustache.Mustache$BlockSegment.executeSegs(Mustache.java:845)
	at com.samskivert.mustache.Mustache$SectionSegment.execute(Mustache.java:866)
```

Is this tracked in a separate ticket @becco ?

**Comment by becco** [comment]
Hi @er1c, thank you for sharing. Hm, when did you start getting this exception? It looks like it may not be related to the fix for this issue.

Could you please open a new issue so we can track it? Thank you!
